#!/bin/sh
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "see bucket creation"
echo ""
echo "https://portal.aws.amazon.com/billing/signup#/start"
echo ""
echo ""
echo "generate access key"
echo ""
echo "https://console.aws.amazon.com/iam/home#/security_credentials"
echo ""
echo "https://docs.aws.amazon.com/AmazonS3/latest/gsg/SigningUpforS3.html"
echo ""
echo "#AWS Access Key ID [None]: AKIAI0youridhereHNTJYI000"
echo "#AWS Secret Access Key => 'dgmbhL__YOUR_KEY_HEREZZZZZZZZZZZZZZZZZZZ',"
echo "#Default region name [None]: us-east-1"
echo "#Default output format [None]: "
echo ""
echo "sign up for an s3 bucket use similar info in the config/environments/production.rb and config/environments/development.rb"
echo ""
echo " config.paperclip_defaults = {   "
echo "  :storage => :s3,  "
echo "    :s3_credentials => {  "
echo "   :bucket => 'your-skytune-bucket-name',  "
echo "   :access_key_id => 'AKIAJGU3P3LZZZZZZZZZ'  "
echo "    :secret_access_key => 'dgmbhL__YOUR_KEY_HEREZZZZZZZZZZZZZZZZZZZ',  "
echo "  :s3_region => 'ap-northeast-1',  "
echo ":s3_host_name => 's3-ap-northeast-1.amazonaws.com'"
echo "   }"
echo "}"
